liwc_vars <- c("Segment","WC","Analytic","Clout","Authentic","Tone","WPS","BigWords","Dic",
               "Linguistic","function.","pronoun","ppron","i","we","you","shehe","they","ipron",
               "det","article","number","prep","auxverb","adverb","conj","negate","verb","adj",
               "quantity","Drives","affiliation","achieve","power","Cognition","allnone","cogproc","insight","cause" ,
               "discrep","tentat","certitude","differ","memory","Affect","tone_pos","tone_neg","emotion","emo_pos","emo_neg","emo_anx","emo_anger","emo_sad","swear",
               "Social","socbehav","prosocial","polite","conflict","moral","comm","socrefs","family","friend",
               "female","male","Culture","politic","ethnicity","tech","Lifestyle","leisure","home","work",
               "money","relig","Physical","health","illness","wellness","mental","substances","sexual","food",
               "death","need","want","acquire","lack","fulfill","fatigue","reward","risk","curiosity",
               "allure","Perception","attention","motion","space","visual","auditory","feeling","time","focuspast",
               "focuspresent","focusfuture","Conversation","netspeak","assent","nonflu","filler","AllPunc","Period","Comma",
               "QMark","Exclam","Apostro","OtherP")
emo_voc_vars <- c("TTR_Overall","TTR_NonDict","Neg_CWR","Pos_CWR","AnxFear_CWR","Anger_CWR","Sadness_CWR",
                  "NegUndiff_CWR","Neg_CCR","Pos_CCR","AnxFear_CCR","Anger_CCR","Sadness_CCR","NegUndiff_CCR",
                  "Neg_Count","Pos_Count","AnxFear_Count","Anger_Count","Sadness_Count","NegUndiff_Count",
                  "Neg_Unique","Pos_Unique","AnxFear_Unique","Anger_Unique","Sadness_Unique","NegUndiff_Unique")
gi_vars <- c("abstract","abstract_distance","abstract_imaterial","abstract_time",
             "academic","academic_doctrine","adjective","adjective_dimensionality",
             "adjective_evaluative","adjective_position","adjective_space",
             "adverb_degree","affect","affect_negative","affect_positive",
             "affection_gain","affection_loss","affection_other", "affection_participants",
             "animate","anomie","arousal","article","certainty","child","cognitive_causal",
             "cognitive_compare","cognitive_evaluate","cognitive_know","cognitive_ought",
             "cognitive_quality","cognitive_quan","cognitive_solve","cognitive_think",
             "cognitive_time","collective","color","communication","communication_format",
             "conjunction_clausal","conjunction_sentential","demonstrative","demonstrative_near",
             "determiner","economic","economic_exchange","emotion","enlightenment_ends",
             "enlightenment_gain","enlightenment_loss","enlightenment_other","enlightenment_participant",
             "feeling","food","frequency","genitive","handled","human","human_female","human_kinship",
             "human_male","idiom","indefinite","indefinite_relative","interjection",
             "interrogative","legal","military","modifier","motivation_complete",
             "motivation_failure","motivation_goal","motivation_means","motivation_need",
             "motivation_persist","motivation_try","negate","no","not","noun","number" ,
             "number_cardinal","number_ordinal","object","object_bodypart","object_building","object_common",
             "object_food","object_natobj","object_tool","object_vehicle","orientation_active","orientation_passive",
             "outlook_negative","outlook_negative_hostile","outlook_positive","outlook_positive_affiliation",
             "overstated","pain","performance","person_kin","person_race","personal_definite","personal_nominative",
             "personal_objective","personal_other","personal_reflexive","personality_individual",
             "personality_relational","place","place_aquatic","place_land","place_region","place_route",
             "place_setting","place_sky","place_social","pleasure","political","power","power_arena","power_authoritative",
             "power_conflict","power_cooperation","power_doctrine","power_end","power_gain","power_loss",
             "power_other","power_participant_authority","power_participant_nonauthority","prearticle","prearticle_count",
             "prearticle_mixed","preposition","process_begin","process_change","process_decrease","process_exert",
             "process_fall","process_fetch","process_increase","process_move","process_natural","process_rise",
             "process_say","process_stay","process_travel","process_vary","pronoun","pronoun_plural","pronoun_relative",
             "pronoun_secondperson","pronoun_thirdperson","rectitude","rectitude_ends","rectitude_ethics","rectitude_gain",
             "rectitude_loss","rectitude_religion","refer_individual","refer_name","refer_nation","refer_othered",
             "refer_others","refer_self","refer_us","refer_you","religion","respect","respect_gain","respect_loss",
             "respect_other","skill","skill_aesthetic","skill_other","skill_participant","social_organization",
             "social_relation","social_ritual","social_role","social_work","spacetime",
             "strength","strength_dominance","submission","superverb","termination",
             "transaction","transaction_gain","transaction_loss","uncertainty","understated",
             "us_state","verb","verb_be","verb_becoming","verb_describe","verb_do",
             "verb_go","verb_have","verb_interpretation","verb_linking",
             "verb_modal","verb_negative","verb_state","verb_to","vice","virtue", 
             "weakness","wealth","wealth_other","wealth_participants",
             "wealth_transaction","wellbeing","wellbeing_concern","wellbeing_gain",
             "wellbeing_loss","wellbeing_physical","wellbeing_psychological","yes")
agen_com_vars <- c("agency","communion")
stress_vars <- c("stress")
prosocial_vars <- c("prosocial")
tms_vars <- c()
uncertainty_vars <- c()
persona_val_vars <- c("openness","self_transcendence","conservation","self_enhancement",
                      "security","conformity","tradition","benevolence","universalism",
                      "self_direction","stimulation","hedonism","achievement","power")
wellbeing_vars <- c()